"""Single-compartment Hay-inspired simulation and surrogate-learning toolkit."""

from .config import MembraneConfig, ProtocolConfig, SimulationConfig
from .dataset import Normalization, generate_dataset, validate_dataset
from .protocols import RandomDrive
from .simulator import CURRENT_NAMES, INPUT_NAMES, STATE_NAMES, SingleCompartmentHay
from .ontology import ONTOLOGY_GROUPS, OntologyGroup
from .faithful import (
    FAITHFUL_CURRENT_NAMES,
    FAITHFUL_INPUT_NAMES,
    FAITHFUL_STATE_NAMES,
    FaithfulHaySoma,
    FaithfulMembraneConfig,
    FaithfulProtocolConfig,
    FaithfulSimulationConfig,
)
from .faithful_dataset import (
    BalancedFaithfulDrive,
    generate_faithful_dataset,
    validate_faithful_dataset,
)
from .micro_neuron import (
    COMPARTMENT_NAMES,
    MICRO_STATE_NAMES,
    SYNAPTIC_REGIONS,
    FourCompartmentHay,
    MicroGeometryConfig,
    MicroHayConfig,
    MicroSynapseConfig,
    ReducedCompartmentGeometry,
)
from .micro_dataset import (
    MICRO_REGIME_NAMES,
    BalancedSpatialSpikeDrive,
    MicroDatasetConfig,
    MicroDriveConfig,
    build_micro_synapse_metadata,
    generate_micro_dataset,
    micro_input_names,
    upgrade_micro_dataset_v1,
    validate_micro_dataset,
)
from .input_only import (
    CausalResidualTCNAdapter,
    InputOnlyCfC,
    InputOnlyBranchELM,
    InputOnlyConvGRU,
    InputOnlyConvLSTM,
    InputOnlyGRU,
    InputOnlyGatedResidualTCN,
    InputOnlyResidualTCN,
    StateDecoder,
    count_trainable_parameters,
    move_hidden,
)
from .event_aware import (
    AuxiliarySpikePhaseLoss,
    MICRO_EVENT_NAMES,
    ConservativeSpikeFineTuneLoss,
    EventAwareStateLoss,
    MicroEventConfig,
    StratifiedWindowSampler,
    classify_micro_events,
    event_catalog,
    replay_gru_gates,
    SpikeGateFocalLoss,
    WaveformConstrainedFineTuneLoss,
)
from .failure_atlas import (
    FailureAtlasConfig,
    aggregate_state_metrics,
    build_failure_atlas,
    checkpoint_gru_spec,
    horizon_metrics,
    inspect_gru_checkpoint,
    load_dataset_context,
    load_prediction_archive,
    match_spikes,
    recurrence_analysis,
    statewise_metrics,
    takens_delay_embedding,
    teacher_centered_waveform_metrics,
    write_activation_diagnostics,
    write_failure_atlas,
)
from .spectral_loss import MultiResolutionSTFTLoss, StateMSEMultiResolutionSTFTLoss

__all__ = [
    "CURRENT_NAMES",
    "INPUT_NAMES",
    "STATE_NAMES",
    "MembraneConfig",
    "Normalization",
    "ONTOLOGY_GROUPS",
    "OntologyGroup",
    "ProtocolConfig",
    "RandomDrive",
    "SimulationConfig",
    "SingleCompartmentHay",
    "generate_dataset",
    "validate_dataset",
    "FAITHFUL_CURRENT_NAMES",
    "FAITHFUL_INPUT_NAMES",
    "FAITHFUL_STATE_NAMES",
    "BalancedFaithfulDrive",
    "FaithfulHaySoma",
    "FaithfulMembraneConfig",
    "FaithfulProtocolConfig",
    "FaithfulSimulationConfig",
    "generate_faithful_dataset",
    "validate_faithful_dataset",
    "COMPARTMENT_NAMES",
    "MICRO_REGIME_NAMES",
    "MICRO_STATE_NAMES",
    "SYNAPTIC_REGIONS",
    "BalancedSpatialSpikeDrive",
    "FourCompartmentHay",
    "MicroDatasetConfig",
    "MicroDriveConfig",
    "MicroGeometryConfig",
    "MicroHayConfig",
    "MicroSynapseConfig",
    "ReducedCompartmentGeometry",
    "build_micro_synapse_metadata",
    "generate_micro_dataset",
    "micro_input_names",
    "upgrade_micro_dataset_v1",
    "validate_micro_dataset",
    "InputOnlyCfC",
    "CausalResidualTCNAdapter",
    "InputOnlyBranchELM",
    "InputOnlyConvGRU",
    "InputOnlyConvLSTM",
    "InputOnlyGRU",
    "InputOnlyGatedResidualTCN",
    "InputOnlyResidualTCN",
    "StateDecoder",
    "count_trainable_parameters",
    "move_hidden",
    "MICRO_EVENT_NAMES",
    "AuxiliarySpikePhaseLoss",
    "ConservativeSpikeFineTuneLoss",
    "EventAwareStateLoss",
    "MicroEventConfig",
    "StratifiedWindowSampler",
    "classify_micro_events",
    "event_catalog",
    "replay_gru_gates",
    "SpikeGateFocalLoss",
    "WaveformConstrainedFineTuneLoss",
    "FailureAtlasConfig",
    "aggregate_state_metrics",
    "build_failure_atlas",
    "checkpoint_gru_spec",
    "horizon_metrics",
    "inspect_gru_checkpoint",
    "load_dataset_context",
    "load_prediction_archive",
    "match_spikes",
    "recurrence_analysis",
    "statewise_metrics",
    "takens_delay_embedding",
    "teacher_centered_waveform_metrics",
    "write_activation_diagnostics",
    "write_failure_atlas",
    "MultiResolutionSTFTLoss",
    "StateMSEMultiResolutionSTFTLoss",
]
